/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/staff/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every account, with its memberships
         * @description ⚠ This is the route that has no equivalent in `/api/v1`, and could
         *     not have one: the product API answers *"which libraries may I name"*,
         *     never *"who is in the system"*.
         *
         *     It reports identity and membership — who exists, and what they may
         *     reach. It deliberately does not report what any individual has been
         *     READING or photographing: "statistics about the users" is a fair thing
         *     for an operator to want, and a per-person activity feed of someone's
         *     own household is a different and much larger power. Aggregate figures
         *     live on the library rows instead.
         */
        get: operations["accounts_api_staff_v1_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Books across every tenant */
        get: operations["books_api_staff_v1_books_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/v1/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every library in the system */
        get: operations["libraries_api_staff_v1_libraries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/v1/libraries/{library_id}/shelves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One library's shelves
         * @description ⚠ Cross-tenant, so it cannot be `/api/v1/shelves`: that resolves the
         *     caller's membership, and a system administrator is a member of
         *     nothing. Note the consequence for the console — an EMPTY list and a
         *     library that does not exist look the same here, deliberately: this
         *     service has no reason to distinguish them, and the library list it
         *     came from is the authority on which ids are real.
         */
        get: operations["shelves_api_staff_v1_libraries__library_id__shelves_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System-wide totals */
        get: operations["overview_api_staff_v1_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/v1/reads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent reads, across every tenant */
        get: operations["reads_api_staff_v1_reads_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/v1/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Books aggregated across every tenant
         * @description ⚠ `library_id` and `status` SELECT works; they never narrow what a
         *     work reports. "In 3 libraries" means three whatever the filter says —
         *     see `StaffQueries.works` for why that had to be a `HAVING`.
         */
        get: operations["works_api_staff_v1_works_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staff/v1/works/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every household's copy of one work
         * @description The key travels as a QUERY parameter, not a path segment.
         *
         *     It is `normalize(title)|normalize(author)` — Hebrew, spaces, a pipe,
         *     and whatever else a title contains. A path segment would need encoding
         *     the console cannot get wrong only by being careful, and `/works/<key>`
         *     would additionally collide with this very route the day a work is
         *     called "instances".
         */
        get: operations["work_instances_api_staff_v1_works_instances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountDTO */
        AccountDTO: {
            /** Created At */
            created_at?: string | null;
            /** Display Name */
            display_name: string;
            /** Email */
            email?: string | null;
            /** Id */
            id: string;
            /** Memberships */
            memberships: components["schemas"]["MembershipDTO"][];
        };
        /** BookDTO */
        BookDTO: {
            /** Added At */
            added_at?: string | null;
            /** Author */
            author: string;
            /** Copy Count */
            copy_count: number;
            /** Id */
            id: string;
            /** Library Id */
            library_id: string;
            /** Shelf Count */
            shelf_count: number;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** BookPageDTO */
        BookPageDTO: {
            /** Items */
            items: components["schemas"]["BookDTO"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
            /**
             * Truncated
             * @description A ranked search stopped at the scan cap, so `total` is honest but pages past the cap are not reachable. Narrow the query.
             */
            truncated: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LibraryDTO */
        LibraryDTO: {
            /** Admins */
            admins: number;
            /** Approved */
            approved: number;
            /** Auto */
            auto: number;
            /** Books */
            books: number;
            /** Captures */
            captures: number;
            /** Copies */
            copies: number;
            /** Created At */
            created_at?: string | null;
            /** Duplicates */
            duplicates: number;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Last Activity */
            last_activity?: string | null;
            /** Lent Out */
            lent_out: number;
            /** Manual */
            manual: number;
            /** Members */
            members: number;
            /** Reads */
            reads: number;
            /** Shelves */
            shelves: number;
        };
        /** MembershipDTO */
        MembershipDTO: {
            /** Joined At */
            joined_at?: string | null;
            /** Library Id */
            library_id: string;
            /** Role */
            role: string;
        };
        /**
         * OverviewDTO
         * @description System-wide totals. Every figure spans every tenant.
         */
        OverviewDTO: {
            /** Accounts */
            accounts: number;
            /** Approved */
            approved: number;
            /**
             * Authenticated
             * @description False when no BOOKSNAP_STAFF_TOKEN is configured, i.e. anyone who can reach this port can read every tenant.
             */
            authenticated: boolean;
            /**
             * Auto
             * @description Books nobody has approved (§5.1's lowest rung). `manual` outranks `approved`, so this — and only this — is 'awaiting'.
             */
            auto: number;
            /** Books */
            books: number;
            /** Captures */
            captures: number;
            /** Copies */
            copies: number;
            /** Duplicates */
            duplicates: number;
            /** Lent Out */
            lent_out: number;
            /** Libraries */
            libraries: number;
            /** Manual */
            manual: number;
            /** Memberships */
            memberships: number;
            /**
             * Orphan Libraries
             * @description Libraries with no membership at all — nobody can see or administer them. Should always be empty; `new_library` mints an admin membership in the same call to keep it so.
             */
            orphan_libraries: string[];
            /** Reads */
            reads: number;
            /** Shelves */
            shelves: number;
        };
        /** ReadDTO */
        ReadDTO: {
            /** Claims */
            claims: number;
            /** Depth */
            depth: number;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Library Id */
            library_id: string;
            /** Mode */
            mode: string;
            /** Shelf Id */
            shelf_id: string;
            /** Shelf Label */
            shelf_label: string;
            /** Started At */
            started_at?: string | null;
            /** Status */
            status: string;
        };
        /** ShelfDTO */
        ShelfDTO: {
            /**
             * Books
             * @description DISTINCT books with a copy standing here, not copies — two copies of one book is one book on the shelf.
             */
            books: number;
            /** Captures */
            captures: number;
            /** Depth Count */
            depth_count: number;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Last Read */
            last_read?: string | null;
            /** Library Id */
            library_id: string;
            /** Virtual */
            virtual: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkDTO
         * @description One book across every tenant — the console's unit since revision 4.
         *
         *     ⚠ There is no `library_id` here, and that is the point of the type. A
         *     system console's question about a book is *how widespread is it*, not
         *     *whose is it*; the per-household instances are a second call
         *     (`/works/instances`), because acting on one is a different, narrower job.
         */
        WorkDTO: {
            /** Author */
            author: string;
            /** Copies */
            copies: number;
            /** First Added */
            first_added?: string | null;
            /**
             * Instances
             * @description Book records, which exceeds `libraries` only if one library holds the same key twice.
             */
            instances: number;
            /**
             * Key
             * @description `app.domain.text.book_key` — `normalize(title)|normalize(author)`. Opaque to the client; pass it back verbatim.
             */
            key: string;
            /** Last Added */
            last_added?: string | null;
            /**
             * Libraries
             * @description How many libraries hold it. Unaffected by the filters — see the query's note on HAVING vs WHERE.
             */
            libraries: number;
            /**
             * Mixed
             * @description Instances disagree about status. A work manual in one house and auto in another has no single status, and hiding that would answer 'anything unapproved?' wrongly.
             */
            mixed: boolean;
            /**
             * Status
             * @description The STRONGEST §5.1 claim any household makes about this work.
             */
            status: string;
            /** Title */
            title: string;
        };
        /** WorkPageDTO */
        WorkPageDTO: {
            /** Items */
            items: components["schemas"]["WorkDTO"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
            /**
             * Truncated
             * @description A ranked search stopped at the scan cap, so `total` is honest but pages past the cap are not reachable. Narrow the query.
             */
            truncated: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    accounts_api_staff_v1_accounts_get: {
        parameters: {
            query?: never;
            header?: {
                "x-booksnap-staff"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    books_api_staff_v1_books_get: {
        parameters: {
            query?: {
                q?: string;
                library_id?: string | null;
                status?: string | null;
                sort?: string;
                ascending?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-booksnap-staff"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookPageDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    libraries_api_staff_v1_libraries_get: {
        parameters: {
            query?: never;
            header?: {
                "x-booksnap-staff"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shelves_api_staff_v1_libraries__library_id__shelves_get: {
        parameters: {
            query?: never;
            header?: {
                "x-booksnap-staff"?: string | null;
                authorization?: string | null;
            };
            path: {
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_api_staff_v1_overview_get: {
        parameters: {
            query?: never;
            header?: {
                "x-booksnap-staff"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reads_api_staff_v1_reads_get: {
        parameters: {
            query?: {
                limit?: number;
                library_id?: string | null;
            };
            header?: {
                "x-booksnap-staff"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    works_api_staff_v1_works_get: {
        parameters: {
            query?: {
                q?: string;
                library_id?: string | null;
                status?: string | null;
                sort?: string;
                ascending?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-booksnap-staff"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkPageDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    work_instances_api_staff_v1_works_instances_get: {
        parameters: {
            query: {
                key: string;
            };
            header?: {
                "x-booksnap-staff"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
