/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or search books
         * @description One endpoint, two modes.
         *
         *     Searching is not a filter on top of a sort — relevance IS the order, so a
         *     `sort` passed alongside `q` would be a promise the server cannot keep.
         *     It is ignored rather than rejected: a UI that keeps a sort control on
         *     screen while the user types should not start returning 400s mid-keystroke.
         */
        get: operations["list_books_api_v1_books_get"];
        put?: never;
        /**
         * Add a book by hand
         * @description A book the reader never found. Lands as ``manual`` — a person typed it,
         *     which is the strongest evidence the system gets.
         */
        post: operations["create_book_api_v1_books_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the whole library (CSV or JSON)
         * @description The honest answer to lock-in (§6): everything, in one file, always.
         *
         *     CSV is written with a UTF-8 BOM. Without it Excel opens a Hebrew CSV as
         *     mojibake, and "my export is broken" is indistinguishable from "your data
         *     is broken".
         */
        get: operations["export_books_api_v1_books_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One book */
        get: operations["get_book_api_v1_books__book_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete from the library (every copy)
         * @description *Delete from the library* — the destructive one of UI_PLAN §5's two
         *     actions. *Remove from shelf* is a different thing entirely and does not
         *     live here; it changes a copy, it does not remove a record.
         */
        delete: operations["delete_book_api_v1_books__book_id__delete"];
        options?: never;
        head?: never;
        /**
         * Fix the title or author
         * @description Editing marks the book ``manual`` (UI_PLAN §5). The domain applies
         *     that; this route only decides what an unresolvable rename returns.
         */
        patch: operations["patch_book_api_v1_books__book_id__patch"];
        trace?: never;
    };
    "/api/v1/books/{book_id}/copies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * "I have another copy"
         * @description §5.1: the ONLY path that creates a second copy. Lands ``manual`` — a
         *     person declaring a duplicate is the strongest evidence the system gets;
         *     no re-read can produce this (`app.domain.book.add_copy`).
         */
        post: operations["create_copy_api_v1_books__book_id__copies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/copies/{copy_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Fix a copy's label, tags or condition
         * @description Object-level metadata, not identity — unlike :func:`patch_book` this
         *     never changes the copy's status (`app.domain.book.edit_copy`).
         */
        patch: operations["patch_copy_api_v1_books__book_id__copies__copy_id__patch"];
        trace?: never;
    };
    "/api/v1/books/{book_id}/copies/{copy_id}/lend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Lend a copy out
         * @description 409 if the copy is already out — return it first (§5.2: one borrower
         *     per copy, or the earlier one is silently lost from "who has my books").
         */
        post: operations["lend_copy_api_v1_books__book_id__copies__copy_id__lend_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/books/{book_id}/copies/{copy_id}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a lent copy returned
         * @description 409 if the copy was never lent, or already marked returned — there is
         *     no open loan to close (`app.domain.book.return_copy`).
         */
        post: operations["return_copy_route_api_v1_books__book_id__copies__copy_id__return_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Capture
         * @description File a photo — with a shelf if one is named, on a fresh one if not.
         *
         *     Returns BOTH the capture and its shelf: when the shelf was auto-created the
         *     client has no other way to learn its id, and a second round trip to
         *     discover the thing you just implicitly made is what gets papered over with
         *     a client-side guess.
         */
        post: operations["create_capture_api_v1_captures_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/captures/{capture_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capture */
        get: operations["get_capture_api_v1_captures__capture_id__get"];
        put?: never;
        post?: never;
        /** Delete Capture */
        delete: operations["delete_capture_api_v1_captures__capture_id__delete"];
        options?: never;
        head?: never;
        /**
         * Bind Capture
         * @description Move a photo to another shelf, another row, or another position.
         *
         *     This is the inline assignment the intake UI performs. Moving to a shelf
         *     that is not one row deeper than the caller thinks is a **409** naming the
         *     declared depth, not a silent clamp: filing a photo at a row that does not
         *     exist would give reconciliation a location with no counterpart in the room.
         */
        patch: operations["bind_capture_api_v1_captures__capture_id__patch"];
        trace?: never;
    };
    "/api/v1/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Image
         * @description Store a photo. **Idempotent by content** — the same bytes return the
         *     same key and write nothing the second time, so a re-upload after a browser
         *     refresh costs a hash rather than a duplicate (§12.3 #13).
         *
         *     ``201`` either way. A conditional ``200``-if-present would leak whether
         *     somebody has already uploaded this exact photo, and the client has nothing
         *     to do differently.
         */
        post: operations["upload_image_api_v1_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Image
         * @description Metadata without the bytes — size, dimensions, original filename.
         */
        get: operations["get_image_api_v1_images__key__get"];
        put?: never;
        post?: never;
        /**
         * Delete Image
         * @description Remove a photo and its renditions.
         *
         *     ⚠ Does NOT check whether a capture still points at it — the stores cannot
         *     see each other's aggregates, and reference counting is P3.5's. Until then
         *     this is for a photo uploaded by mistake, and a capture whose image was
         *     deleted shows a missing picture rather than disappearing.
         */
        delete: operations["delete_image_api_v1_images__key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/{key}/full": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Full
         * @description The stored photo, EXIF already applied — the same pixels the engine
         *     reads, which is what makes a review screen trustworthy.
         */
        get: operations["get_full_api_v1_images__key__full_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/images/{key}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Thumb
         * @description A JPEG thumbnail for the review grid.
         *
         *     Whether it was cached at upload or derived just now is the adapter's
         *     business — this route asks for a variant and gets bytes. Keeping the
         *     rendering behind the port is also what keeps the API layer out of the
         *     image-processing business, which the layering test forbids outright.
         */
        get: operations["get_thumb_api_v1_images__key__thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service and library identity */
        get: operations["get_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shelves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Shelves
         * @description Every shelf, named ones first and alphabetically, then unnamed ones
         *     oldest-first. Not paged — a personal library has tens of shelves.
         */
        get: operations["list_shelves_api_v1_shelves_get"];
        put?: never;
        /**
         * Create Shelf
         * @description Declare a shelf up front. Every field is optional (identity is free).
         *
         *     Depth is not settable here on purpose — a shelf starts one row deep and
         *     gains rows through :func:`add_a_row_behind`, because §5.7 makes the second
         *     row a declaration rather than a number to guess at during creation.
         */
        post: operations["create_shelf_api_v1_shelves_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shelves/{shelf_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shelf */
        get: operations["get_shelf_api_v1_shelves__shelf_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Shelf
         * @description Remove a shelf that holds no photos. **409** if it does.
         *
         *     Not a cascade: its captures are the record a re-read diffs against (§5.6).
         *     This is for the shelf created by mistake, not for clearing one out.
         */
        delete: operations["delete_shelf_api_v1_shelves__shelf_id__delete"];
        options?: never;
        head?: never;
        /**
         * Patch Shelf
         * @description Name a shelf, or clear the name — ``""`` is a legal value, not a
         *     missing one, because a label the owner no longer wants should not be kept
         *     just to avoid an empty string.
         */
        patch: operations["patch_shelf_api_v1_shelves__shelf_id__patch"];
        trace?: never;
    };
    "/api/v1/shelves/{shelf_id}/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shelf Captures */
        get: operations["list_shelf_captures_api_v1_shelves__shelf_id__captures_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shelves/{shelf_id}/depths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add A Row Behind
         * @description *"Add a row behind this one"* (§5.7) — the declaration that cannot be
         *     detected, because nothing in a photo says "this is the row behind"; the
         *     front books are simply absent.
         *
         *     Its own endpoint rather than a ``depth_count`` field so the client cannot
         *     set it to 5 in one step and leave three rows nobody photographed. Refused
         *     on the wishlist, which has no behind.
         */
        post: operations["add_a_row_behind_api_v1_shelves__shelf_id__depths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_image_api_v1_images_post */
        Body_upload_image_api_v1_images_post: {
            /**
             * File
             * @description The photo. Decoded to validate it.
             */
            file: string;
            /**
             * Filename
             * @description Original name, for the review screen. Falls back to the upload's own name; never used to decide the format.
             * @default
             */
            filename: string;
        };
        /**
         * BookCreate
         * @description Add a book the reader never found. Lands as ``manual`` with one copy.
         */
        BookCreate: {
            /**
             * Author
             * @default
             */
            author: string;
            /** Title */
            title: string;
        };
        /**
         * BookDTO
         * @description A book and its copies.
         *
         *     Copies are embedded in the LIST response, not fetched per row. With one
         *     copy per book on the real data that is roughly a 2x payload, and the
         *     alternative — the book surface firing a request per card (UI_PLAN §5) —
         *     is far worse. Revisit if a library ever has many multi-copy books.
         */
        BookDTO: {
            /** Added At */
            added_at?: string | null;
            /**
             * Author
             * @default
             */
            author: string;
            /**
             * Author Key
             * @description Normalized author, the key the author chip groups on (§5.1 — authors are strings, not entities).
             */
            author_key: string;
            /** Copies */
            copies: components["schemas"]["CopyDTO"][];
            /** Copy Count */
            copy_count: number;
            /** Id */
            id: string;
            /** Shared Book Id */
            shared_book_id?: string | null;
            /**
             * Status
             * @description auto | approved | manual — the strongest claim among this book's copies.
             */
            status: string;
            /** Title */
            title: string;
            work: components["schemas"]["WorkFieldsDTO"];
        };
        /**
         * BookPageDTO
         * @description One page plus the total, so the client can render "1-20 of 251"
         *     without a second round trip.
         */
        BookPageDTO: {
            /** Items */
            items: components["schemas"]["BookDTO"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * BookPatch
         * @description Fix a title or an author by hand. Either field, or both.
         *
         *     Saving marks the book ``manual`` — a human decision outranking an auto one
         *     (UI_PLAN §5). That is applied by the domain, not here.
         */
        BookPatch: {
            /** Author */
            author?: string | null;
            /** Title */
            title?: string | null;
        };
        /**
         * BookSort
         * @description Sort orders §6 lists as "Must". ``TITLE``/``AUTHOR`` sort by NORMALIZED
         *     forms, so Hebrew orders sensibly regardless of nikud, geresh or a leading
         *     particle in the stored string.
         *
         *     ``AUTHOR`` orders by SURNAME (``app.domain.text.author_sort_key``), the way
         *     a shelf is filed — not by the stored string, which would put every author
         *     under their given name. Every implementation must agree; the contract
         *     suite asserts it against each one.
         * @enum {string}
         */
        BookSort: "title" | "author" | "recently_added";
        /**
         * CaptureBinding
         * @description What :meth:`create` produced — the photo AND the shelf it landed on.
         *
         *     Both, never just the capture: when the shelf was auto-created the client
         *     has no other way to learn its id, and a second round trip to discover the
         *     thing you just implicitly made is the sort of gap that gets papered over
         *     with a client-side guess. Same reasoning as the copy routes returning the
         *     whole ``BookDTO``.
         */
        CaptureBinding: {
            capture: components["schemas"]["CaptureDTO"];
            shelf: components["schemas"]["ShelfDTO"];
            /**
             * Shelf Created
             * @description True when no shelf_id was given and one was made.
             */
            shelf_created: boolean;
        };
        /**
         * CaptureCreate
         * @description File a photo.
         *
         *     ``shelf_id`` is optional and that is the point of P2.2: a photo that names
         *     no shelf gets a fresh unnamed one, because a capture with no shelf is a
         *     read with nothing to reconcile against (§5.6). *"Unassigned"* on screen
         *     means *not yet named*, never *not yet filed*.
         */
        CaptureCreate: {
            /**
             * Depth
             * @default 1
             */
            depth: number;
            /** Image Id */
            image_id?: string | null;
            /**
             * Order
             * @description Omit to append after the last photo at this shelf+depth.
             */
            order?: number | null;
            /** Shelf Id */
            shelf_id?: string | null;
        };
        /**
         * CaptureDTO
         * @description One photo of part of a shelf, keyed by ``(shelf, depth, order)``.
         */
        CaptureDTO: {
            /** Captured At */
            captured_at?: string | null;
            /**
             * Depth
             * @description Which row front-to-back. 1-based.
             */
            depth: number;
            /** Id */
            id: string;
            /**
             * Image Id
             * @description Reference, never bytes — blobs live behind BlobStore (P3.5). Also what identifies an unnamed shelf on screen.
             */
            image_id?: string | null;
            /**
             * Order
             * @description Position among this shelf+depth's photos, left-to-right or right-to-left per the shelf's reading direction.
             */
            order: number;
            /** Shelf Id */
            shelf_id: string;
        };
        /**
         * CapturePatch
         * @description Re-bind a photo: move it to another shelf, another row, or another
         *     position. This is the inline assignment the intake UI performs.
         */
        CapturePatch: {
            /** Depth */
            depth?: number | null;
            /** Order */
            order?: number | null;
            /** Shelf Id */
            shelf_id?: string | null;
        };
        /**
         * CopyCreate
         * @description *"I have another copy"* (§5.1) — the only path that creates a second
         *     physical object. No ``shelf_id`` here: shelves don't exist until P2.1, so
         *     every copy today is unlocated regardless of how it was created.
         */
        CopyCreate: {
            /**
             * Condition
             * @default
             */
            condition: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** Tags */
            tags?: string[];
        };
        /**
         * CopyDTO
         * @description One physical object. Created only by a human action (§5.1).
         */
        CopyDTO: {
            /** Acquired At */
            acquired_at?: string | null;
            /**
             * Condition
             * @default
             */
            condition: string;
            /**
             * Depth
             * @description Row front-to-back. A located copy always has one; an unlocated copy has neither shelf nor depth (§5.7).
             */
            depth?: number | null;
            /** Id */
            id: string;
            /**
             * Label
             * @default
             */
            label: string;
            /** @description Most recent provenance entry, if any. */
            last_seen?: components["schemas"]["SightingDTO"] | null;
            lending?: components["schemas"]["LendingDTO"] | null;
            /** Shelf Id */
            shelf_id?: string | null;
            /**
             * Sighting Count
             * @description Length of the provenance list; the list itself is on the book detail, not in every row.
             */
            sighting_count: number;
            /** Status */
            status: string;
            /** Tags */
            tags?: string[];
        };
        /**
         * CopyPatch
         * @description Fix a copy's own label/tags/condition. Object-level, unlike
         *     :class:`BookPatch` — describing "paperback, torn cover" is not a claim
         *     about the book's identity, so unlike a title/author edit this does not
         *     change the copy's status.
         */
        CopyPatch: {
            /** Condition */
            condition?: string | null;
            /** Label */
            label?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImageDTO
         * @description A stored photo. Bytes are served from ``/images/{key}/full|thumb``.
         */
        ImageDTO: {
            /** Content Type */
            content_type: string;
            /**
             * Filename
             * @description Original name, for the review screen only.
             * @default
             */
            filename: string;
            /**
             * Height
             * @description Dimensions of the stored, upright image — so the grid can reserve the right aspect ratio before the bytes arrive.
             * @default 0
             */
            height: number;
            /**
             * Key
             * @description Storage key AND content hash. Re-uploading the same photo returns this same key, so a URL built from it can be cached forever — different bytes can never reuse it.
             */
            key: string;
            /** Sha256 */
            sha256: string;
            /**
             * Size
             * @description Bytes as STORED, after EXIF normalisation.
             */
            size: number;
            /**
             * Width
             * @default 0
             */
            width: number;
        };
        /**
         * LendRequest
         * @description *"Lend it out"*. ``lent_at`` is server time (the ``Clock``, like
         *     ``added_at``), never client-supplied — a borrow date is a fact about when
         *     the server recorded the action, not something the caller should be able
         *     to backdate.
         */
        LendRequest: {
            /** Due At */
            due_at?: string | null;
            /** Lent To */
            lent_to: string;
        };
        /**
         * LendingDTO
         * @description Per copy, never per book — you lend an object, not a work.
         */
        LendingDTO: {
            /** Due At */
            due_at?: string | null;
            /**
             * Is Out
             * @description Derived: no returned_at yet.
             */
            is_out: boolean;
            /** Lent At */
            lent_at: string;
            /** Lent To */
            lent_to: string;
            /** Returned At */
            returned_at?: string | null;
        };
        /**
         * LibraryRefDTO
         * @description The tenant reference the client echoes back on every request.
         *
         *     Present from the very first endpoint on purpose: the client is
         *     tenant-aware from P1.0 (§1.3), even though there is exactly one library
         *     until pillar 3.
         */
        LibraryRefDTO: {
            /**
             * Id
             * @description Opaque library identifier.
             */
            id: string;
            /**
             * Label
             * @description Human-readable library name.
             */
            label: string;
        };
        /**
         * MetaResponse
         * @description Service identity + the caller's resolved library.
         */
        MetaResponse: {
            /**
             * Api Version
             * @description API major version, e.g. 'v1'.
             */
            api_version: string;
            /**
             * App
             * @description Service name.
             */
            app: string;
            /** @description Library resolved for this caller. */
            library: components["schemas"]["LibraryRefDTO"];
            /**
             * Version
             * @description Server package version.
             */
            version: string;
        };
        /**
         * ShelfCreate
         * @description Declare a shelf. Every field optional — see :class:`ShelfDTO.label`.
         */
        ShelfCreate: {
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Virtual
             * @default false
             */
            virtual: boolean;
        };
        /**
         * ShelfDTO
         * @description A shelf's identity. No address — that is pillar 6 (plan §1.1).
         */
        ShelfDTO: {
            /**
             * Capture Count
             * @description Photos filed against this shelf, across every depth.
             */
            capture_count: number;
            /** Created At */
            created_at?: string | null;
            /**
             * Depth Count
             * @description Rows front-to-back, declared by the owner — never detected (§5.7). 1 unless a row behind was added.
             */
            depth_count: number;
            /** Id */
            id: string;
            /**
             * Label
             * @description Optional. Empty is normal: identity is free, so a shelf is never required to be named. An unnamed one is shown by the image it came from.
             * @default
             */
            label: string;
            /**
             * Virtual
             * @description The wishlist. Excluded from shelf listings by default.
             */
            virtual: boolean;
        };
        /**
         * ShelfPatch
         * @description Name a shelf, or clear the name. ``depth_count`` is deliberately NOT
         *     here: adding a row behind is its own endpoint, because §5.7 makes it an
         *     explicit declaration rather than a number to nudge.
         */
        ShelfPatch: {
            /** Label */
            label?: string | null;
        };
        /**
         * SightingDTO
         * @description One entry of a copy's append-only provenance (§5.2).
         */
        SightingDTO: {
            /** Captured At */
            captured_at?: string | null;
            /**
             * Depth
             * @description Which row front-to-back (§5.7). Travels WITH shelf_id — both null or both set.
             */
            depth?: number | null;
            /** Run Id */
            run_id: string;
            /**
             * Shelf Id
             * @description Where this sighting happened. Null for the 251 imported books, whose recorded evidence is only run+spine.
             */
            shelf_id?: string | null;
            /** Spine Id */
            spine_id: string;
        };
        /**
         * Status
         * @description auto < approved < manual.
         *
         *     ``auto``      the pipeline claimed it at AUTO tier and nobody has looked;
         *     ``approved``  a human confirmed the claim;
         *     ``manual``    a human typed or corrected it.
         *
         *     Ordering matters because it is the whole content of "a human decision
         *     outranks an auto one" (`booksnap/library.py::add_book`, VISION §5.6).
         * @enum {string}
         */
        Status: "auto" | "approved" | "manual";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WorkFieldsDTO
         * @description Book-level user fields. You don't rate your second copy differently.
         */
        WorkFieldsDTO: {
            /**
             * Notes
             * @default
             */
            notes: string;
            /** Rating */
            rating?: number | null;
            /** Read Status */
            read_status?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_books_api_v1_books_get: {
        parameters: {
            query?: {
                /** @description Hebrew search over title and author. When present the results are ordered by RELEVANCE and `sort`/`ascending` are ignored — the order is the answer. */
                q?: string | null;
                /** @description title / author sort on the NORMALIZED forms, so Hebrew orders sensibly. */
                sort?: components["schemas"]["BookSort"];
                ascending?: boolean;
                status?: components["schemas"]["Status"] | null;
                /** @description Normalized author, from a book's author_key. */
                author_key?: string | null;
                /** @description True for the "who has my books" view: books with at least one copy currently lent out. */
                lent_out?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookPageDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_book_api_v1_books_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_books_api_v1_books_export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_v1_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_book_api_v1_books__book_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_book_api_v1_books__book_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_copy_api_v1_books__book_id__copies_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_copy_api_v1_books__book_id__copies__copy_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                copy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopyPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lend_copy_api_v1_books__book_id__copies__copy_id__lend_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                copy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LendRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    return_copy_route_api_v1_books__book_id__copies__copy_id__return_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
                copy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_capture_api_v1_captures_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureBinding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_capture_api_v1_captures__capture_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_capture_api_v1_captures__capture_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bind_capture_api_v1_captures__capture_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                capture_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CapturePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureBinding"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_image_api_v1_images_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_image_api_v1_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_api_v1_images__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_image_api_v1_images__key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_full_api_v1_images__key__full_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thumb_api_v1_images__key__thumb_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
    list_shelves_api_v1_shelves_get: {
        parameters: {
            query?: {
                /** @description Include the wishlist. Excluded by default: it holds books the owner does not own, so counting it inflates both the shelf list and the apparent size of the library. */
                include_virtual?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_shelf_api_v1_shelves_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShelfCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shelf_api_v1_shelves__shelf_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shelf_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shelf_api_v1_shelves__shelf_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shelf_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_shelf_api_v1_shelves__shelf_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shelf_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShelfPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shelf_captures_api_v1_shelves__shelf_id__captures_get: {
        parameters: {
            query?: {
                /** @description Narrow to one row front-to-back. §5.6's not-seen rule and the diff view are per depth, and §5.7 #2 forbids merging overlaps across depths. */
                depth?: number | null;
            };
            header?: never;
            path: {
                shelf_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureDTO"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_a_row_behind_api_v1_shelves__shelf_id__depths_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shelf_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfDTO"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
