/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service and library identity */
        get: operations["get_meta_api_v1_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * LibraryRefDTO
         * @description The tenant reference the client echoes back on every request.
         *
         *     Present from the very first endpoint on purpose: the client is
         *     tenant-aware from P1.0 (§1.3), even though there is exactly one library
         *     until pillar 3.
         */
        LibraryRefDTO: {
            /**
             * Id
             * @description Opaque library identifier.
             */
            id: string;
            /**
             * Label
             * @description Human-readable library name.
             */
            label: string;
        };
        /**
         * MetaResponse
         * @description Service identity + the caller's resolved library.
         *
         *     The one endpoint P1.0 ships. It carries no domain data — its job is to
         *     prove the whole path end to end: principal -> library -> DTO -> OpenAPI
         *     schema -> generated TS type -> typed fetch in a React component.
         */
        MetaResponse: {
            /**
             * Api Version
             * @description API major version, e.g. 'v1'.
             */
            api_version: string;
            /**
             * App
             * @description Service name.
             */
            app: string;
            /** @description Library resolved for this caller. */
            library: components["schemas"]["LibraryRefDTO"];
            /**
             * Version
             * @description Server package version.
             */
            version: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_meta_api_v1_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaResponse"];
                };
            };
        };
    };
}
